FROM python:3.10
  
  # Python'un outputları tam göstərməsi üçün
ENV PYTHONUNBUFFERED 1
ENV APP_ROOT /code
ENV DEBUG False
  
  # PostgreSQL üçün psycopg2 quraşdırılmasını təmin et
RUN apt-get update && apt-get install -y libpq-dev gcc
  
  # Tələb olunan Python kitabxanalarını quraşdır
ADD requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
  
  # Proyekt kodlarını konteynerə əlavə et
WORKDIR ${APP_ROOT}
ADD . ${APP_ROOT}
  
  # Django static fayllarını topla
RUN if [ -f manage.py ]; then python manage.py collectstatic --noinput; fi
  
  # Portu açıq saxla
EXPOSE 8000
  
  # Django serverini başlat
CMD ["gunicorn", "--chdir", "/code", "config.wsgi:application", "--bind", "0.0.0.0:8000"]
