version: '3'

services:
  postgres:
    container_name: postgres-db
    image: postgres:14  # PostgreSQL 14 versiyasına keçirik
    ports:
      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  django_app:
    container_name: django
    build: .
    restart: "always"
    env_file: .env
    environment:
      - VIRTUAL_HOST=157.180.28.125,edu-po.com
      - VIRTUAL_PORT=8000
      - TIMEOUT=300
      - HTTP_PORT=8000
      - STATS_PORT=8001
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx konfiqurasiyasını daxil edin
      - ./staticfiles:/static  # Static faylları təmin et
      - ./media:/media  # Media faylları təmin et
    ports:
      - "80:80"  # HTTP port
      - "443:443"  # HTTPS port (əgər SSL istifadə edirsinizsə)
    depends_on:
      - django_app  # Nginx əvvəlcə Django konteynerinə ehtiyac duyur
    networks:
      - nginx-proxy  # Nginx proxy şəbəkəsinə qoşulun

networks:
  default:
    external:
      name: nginx-proxy  # External şəbəkə, əgər nginx-proxy konteyneriniz varsa
  web:
    external: true
