# Generated by Django 4.2 on 2025-02-23 09:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Ad')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Soyad')),
                ('user_image', models.ImageField(blank=True, max_length=5000, null=True, upload_to='user_cdn_profie', verbose_name='Profil şəkli')),
                ('activation_code', models.CharField(blank=True, max_length=120, null=True)),
                ('password_reset_code', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('usertype', models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager')], null=True, verbose_name='İstifadəçi növü')),
                ('phone_number', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Telefon nömrəsi')),
                ('description', models.TextField(null=True, verbose_name='Ətraflı məlumat')),
                ('adress', models.CharField(max_length=5000, null=True, verbose_name='Ünvan')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'Hesab',
                'verbose_name_plural': 'Hesablar',
                'ordering': ['-id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500, verbose_name='Company name')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='Company logo')),
                ('address', models.CharField(max_length=1500, null=True, verbose_name='Company address')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=12000, null=True, verbose_name='Phone number')),
                ('website', models.CharField(blank=True, max_length=1200, null=True, verbose_name='Website')),
                ('package_company', models.IntegerField(blank=True, choices=[(1, 'Free'), (2, 'Silver'), (3, 'Gold'), (4, 'Premium')], null=True, verbose_name='Company Package')),
                ('tax_id', models.CharField(max_length=1200, verbose_name='Tax id')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-reg_date'],
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='accounts.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
