# Generated by Django 4.2 on 2025-01-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500, verbose_name='Company name')),
                ('tax_id', models.CharField(max_length=1200, verbose_name='Tax id')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Registration date')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-reg_date'],
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='accounts.company', verbose_name='Company'),
        ),
    ]
