# Generated by Django 4.2 on 2025-03-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('az', 'Azerbaijani'), ('ru', 'Russian')], default='en', max_length=5, null=True),
        ),
    ]
