# Generated by Django 4.2 on 2025-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_myuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='package_company',
            field=models.IntegerField(blank=True, choices=[(1, 'Free'), (2, 'Silver'), (3, 'Gold'), (4, 'Premium')], null=True, verbose_name='Company Package'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='usertype',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager')], null=True, verbose_name='İstifadəçi növü'),
        ),
    ]
