# Generated by Django 4.2 on 2025-03-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_myuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('az', 'Azerbaijani')], default='en', max_length=5, null=True),
        ),
    ]
