# Generated by Django 4.2 on 2025-03-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='usertype',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Assistant')], null=True, verbose_name='İstifadəçi növü'),
        ),
    ]
