# Generated by Django 4.2 on 2025-03-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='adress',
        ),
        migrations.AddField(
            model_name='myuser',
            name='position',
            field=models.CharField(max_length=5000, null=True, verbose_name='Position'),
        ),
    ]
