# Generated by Django 4.2 on 2025-02-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_address_company_company_logo_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='companies/', verbose_name='Company logo'),
        ),
    ]
