# Generated by Django 4.2 on 2025-03-16 07:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1200, verbose_name='Sual')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Cavab')),
                ('place', models.IntegerField(null=True, verbose_name='Sıra nömrəsi')),
                ('draft', models.BooleanField(default=True, verbose_name='Saytda yayımlansın?')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['place'],
            },
        ),
    ]
