# Generated by Django 4.2 on 2025-03-16 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_remove_myuser_adress_myuser_position'),
        ('main', '0002_support_supportticketmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='support',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='support',
            name='file',
            field=models.FileField(blank=True, upload_to='support_files/', verbose_name='Attachment'),
        ),
    ]
