# Generated by Django 4.2 on 2025-05-09 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_myuser_adress_myuser_position'),
        ('educlass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_company', to='accounts.company', verbose_name='Company'),
        ),
    ]
