# Generated by Django 4.2 on 2025-05-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educlass', '0002_course_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_type',
            field=models.IntegerField(choices=[(1, 'Day'), (2, 'Week'), (3, 'Month')], null=True, verbose_name='Duration Type'),
        ),
    ]
