# Generated by Django 4.2 on 2025-05-09 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educlass', '0003_course_duration_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Category',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_category', to='educlass.category', verbose_name='Category'),
        ),
    ]
