# Generated by Django 4.2 on 2025-05-09 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_myuser_adress_myuser_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educlass', '0004_remove_course_category_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_user', to=settings.AUTH_USER_MODEL, verbose_name='Course Author'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_company', to='accounts.company', verbose_name='Course Company'),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_author', to=settings.AUTH_USER_MODEL, verbose_name='Course Author'),
        ),
    ]
