# Generated by Django 4.2 on 2025-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educlass', '0005_category_author_category_company_course_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
