# Generated by Django 4.2 on 2025-05-10 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_myuser_adress_myuser_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educlass', '0007_instructor_room_class_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_author', to=settings.AUTH_USER_MODEL, verbose_name='Course Author'),
        ),
        migrations.AddField(
            model_name='class',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_company', to='accounts.company', verbose_name='Company'),
        ),
    ]
