# Generated by Django 4.2 on 2025-05-10 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_myuser_adress_myuser_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educlass', '0008_class_author_class_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_author', to=settings.AUTH_USER_MODEL, verbose_name='Course Author'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_company', to='accounts.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='room',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_author', to=settings.AUTH_USER_MODEL, verbose_name='Course Author'),
        ),
        migrations.AddField(
            model_name='room',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_company', to='accounts.company', verbose_name='Company'),
        ),
    ]
