# Generated by Django 4.2 on 2025-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educlass', '0009_instructor_author_instructor_company_room_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Upcoming'), (3, 'Completed')], verbose_name='Status'),
        ),
    ]
