# Generated by Django 4.2 on 2025-01-11 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='Customer ID')),
                ('first_name', models.CharField(max_length=1500, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=1500, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=1500, verbose_name='Mobile number')),
                ('email', models.EmailField(max_length=1500, verbose_name='Email')),
                ('stage', models.IntegerField(choices=[(1, 'Lead'), (2, 'Qualified'), (3, 'Pending'), (4, 'Postponed'), (5, 'Contracted'), (6, 'Canceled'), (7, 'Rejected')], verbose_name='Stage')),
                ('course_or_trainings', models.IntegerField(choices=[(1, 'Course'), (2, 'Training')], verbose_name='Course/Trainings')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], verbose_name='Gender')),
                ('next_step', models.IntegerField(choices=[(1, 'Follow up'), (2, 'Retarget'), (3, 'Closed')], verbose_name='Next Step')),
                ('status', models.IntegerField(choices=[(1, 'Student'), (2, 'Employed'), (3, 'Unemployed')], verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=1, max_digits=1000000000, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, null=True, unique=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_company', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-id'],
            },
        ),
    ]
