# Generated by Django 4.2 on 2025-01-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='location',
            field=models.IntegerField(choices=[(1, 'Ağcabədi'), (2, 'Ağdam'), (3, 'Ağdaş'), (4, 'Ağstafa'), (5, 'Ağsu'), (6, 'Astara'), (7, 'Bakı'), (8, 'Balakən'), (9, 'Bərdə'), (10, 'Beyləqan'), (11, 'Biləsuvar'), (12, 'Cəbrayıl'), (13, 'Cəlilabad'), (14, 'Daşkəsən'), (15, 'Füzuli'), (16, 'Gədəbəy'), (17, 'Gəncə'), (18, 'Göyçay'), (19, 'Göygöl'), (20, 'Hacıqabul'), (21, 'İmişli'), (22, 'İsmayıllı'), (23, 'Kəlbəcər'), (24, 'Kürdəmir'), (25, 'Laçın'), (26, 'Lerik'), (27, 'Lənkəran'), (28, 'Masallı'), (29, 'Mingəçevir'), (30, 'Naftalan'), (31, 'Naxçıvan'), (32, 'Neftçala'), (33, 'Oğuz'), (34, 'Qəbələ'), (35, 'Qax'), (36, 'Qazax'), (37, 'Qobustan'), (38, 'Quba'), (39, 'Qubadlı'), (40, 'Qusar'), (41, 'Saatlı'), (42, 'Sabirabad'), (43, 'Salyan'), (44, 'Şabran'), (45, 'Şamaxı'), (46, 'Şəki'), (47, 'Şəmkir'), (48, 'Şirvan'), (49, 'Siyəzən'), (50, 'Sumqayıt'), (51, 'Tərtər'), (52, 'Tovuz'), (53, 'Ucar'), (54, 'Xaçmaz'), (55, 'Xankəndi'), (56, 'Xırdalan'), (57, 'Xızı'), (58, 'Yardımlı'), (59, 'Yevlax'), (60, 'Zaqatala'), (61, 'Zəngilan'), (62, 'Zərdab')], null=True, verbose_name='Location'),
        ),
    ]
