# Generated by Django 4.2 on 2025-01-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customers_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='Company ID')),
                ('name', models.CharField(max_length=1500, verbose_name='Company Name')),
                ('industry', models.IntegerField(choices=[(1, 'Technology'), (2, 'Healthcare'), (3, 'Finance'), (4, 'Education'), (5, 'Retail'), (6, 'Manufacturing'), (7, 'Real Estate'), (8, 'Entertainment'), (9, 'Energy'), (10, 'Transportation'), (11, 'Telecommunications'), (12, 'Hospitality'), (13, 'Construction'), (14, 'Legal'), (15, 'Agriculture'), (16, 'Automotive'), (17, 'Aerospace'), (18, 'Pharmaceutical'), (19, 'Insurance'), (20, 'Media'), (21, 'Consumer Goods'), (22, 'Food & Beverage'), (23, 'Mining'), (24, 'Utilities'), (25, 'Non-profit'), (26, 'Environmental'), (27, 'Government'), (28, 'Sports'), (29, 'Arts & Culture'), (30, 'Security')], null=True, verbose_name='Industry')),
                ('contact_person', models.CharField(max_length=1500, verbose_name='Contact Person')),
                ('position', models.CharField(max_length=1500, verbose_name='Position')),
                ('email', models.EmailField(max_length=1500, verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=15, verbose_name='Mobile Number')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Contract Number')),
                ('sales', models.CharField(max_length=255, verbose_name='Sales')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='customers',
            name='location',
            field=models.IntegerField(choices=[(1, 'Abşeron (Xırdalan şəhəri)'), (2, 'Ağcabədi'), (3, 'Ağdam (Quzanlı qəsəbəsi)'), (4, 'Ağdaş'), (5, 'Ağdərə'), (6, 'Ağstafa'), (7, 'Ağsu'), (8, 'Astara'), (9, 'Babək'), (10, 'Balakən'), (11, 'Beyləqan'), (12, 'Bərdə'), (13, 'Biləsuvar'), (14, 'Cəbrayıl'), (15, 'Cəlilabad'), (16, 'Culfa'), (17, 'Daşkəsən'), (18, 'Füzuli'), (19, 'Gədəbəy'), (20, 'Goranboy'), (21, 'Göyçay'), (22, 'Göygöl'), (23, 'Hacıqabul'), (24, 'Xaçmaz'), (25, 'Xızı'), (26, 'Xocalı'), (27, 'Xocavənd'), (28, 'İmişli'), (29, 'İsmayıllı'), (30, 'Kəlbəcər'), (31, 'Kəngərli (Qıvraq qəsəbəsi)'), (32, 'Kürdəmir'), (33, 'Qax'), (34, 'Qazax'), (35, 'Qəbələ'), (36, 'Qobustan'), (37, 'Quba'), (38, 'Qubadlı'), (39, 'Qusar'), (40, 'Laçın'), (41, 'Lerik'), (42, 'Lənkəran'), (43, 'Masallı'), (44, 'Neftçala'), (45, 'Oğuz'), (46, 'Ordubad'), (47, 'Saatlı'), (48, 'Sabirabad'), (49, 'Salyan'), (50, 'Samux'), (51, 'Sədərək (Heydərabad qəsəbəsi)'), (52, 'Siyəzən'), (53, 'Şabran'), (54, 'Şahbuz'), (55, 'Şamaxı'), (56, 'Şəki'), (57, 'Şəmkir'), (58, 'Şərur'), (59, 'Şuşa'), (60, 'Tərtər'), (61, 'Tovuz'), (62, 'Ucar'), (63, 'Yardımlı'), (64, 'Yevlax'), (65, 'Zaqatala'), (66, 'Zəngilan'), (67, 'Zərdab')], null=True, verbose_name='Location'),
        ),
    ]
