# Generated by Django 4.2 on 2025-03-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_calendarevent_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(blank=True, choices=[('#007bff', 'Blue'), ('#28a745', 'Green'), ('#dc3545', 'Red'), ('#ffc107', 'Yellow'), ('#17a2b8', 'Cyan'), ('#6f42c1', 'Purple'), ('#fd7e14', 'Orange'), ('#e83e8c', 'Pink'), ('#20c997', 'Teal'), ('#343a40', 'Dark'), ('#6c757d', 'Gray')], max_length=10),
        ),
    ]
