# Generated by Django 4.2 on 2025-03-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_calendarevent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1, verbose_name='Course Status'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.IntegerField(choices=[(1, 'Meeting'), (2, 'Appointment'), (3, 'Event')], null=True, verbose_name='Event Type'),
        ),
    ]
