# Generated by Django 4.2 on 2025-01-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_usercompany_alter_customers_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompany',
            name='price',
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='contract_number',
            field=models.CharField(max_length=50, verbose_name='Total contract'),
        ),
        migrations.AlterField(
            model_name='usercompany',
            name='sales',
            field=models.CharField(max_length=255, verbose_name='Total Sales'),
        ),
    ]
