# Generated by Django 4.2 on 2025-01-18 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0004_remove_usercompany_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('position', models.CharField(max_length=1500, verbose_name='Position')),
                ('reg_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500, verbose_name='Course Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='usercompany',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Qualified'), (3, 'Processing'), (4, 'Postponed'), (5, 'Contracted'), (6, 'Rejected')], null=True, verbose_name='Industry')),
                ('participants', models.CharField(max_length=1200, verbose_name='Participants')),
                ('order_date', models.DateField(auto_now_add=True, null=True, verbose_name='Order Date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_owner', to=settings.AUTH_USER_MODEL)),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_person', to='crm.contactperson', verbose_name='Contact Person')),
                ('user_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.usercompany', verbose_name='User Company')),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='contactperson',
            name='user_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_company_contact', to='crm.usercompany', verbose_name='Company'),
        ),
    ]
