# Generated by Django 4.2 on 2025-03-09 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0005_course_author_course_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Course Author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Course Company'),
        ),
    ]
