# Generated by Django 4.2 on 2025-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_order_options_usercompany_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Qualified'), (3, 'Processing'), (4, 'Postponed'), (5, 'Contracted'), (6, 'Rejected')], null=True, verbose_name='Status'),
        ),
    ]
