# Generated by Django 4.2 on 2025-03-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_course_author_alter_course_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=1200, null=True, verbose_name='Duration'),
        ),
    ]
