# Generated by Django 4.2 on 2025-03-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_type',
            field=models.IntegerField(choices=[(1, 'Day'), (2, 'Week'), (3, 'Month')], null=True, verbose_name='Duration Type'),
        ),
    ]
