# Generated by Django 4.2 on 2025-01-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_order_order_id_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompany',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='usercompany',
            name='position',
        ),
    ]
