# Generated by Django 4.2 on 2025-01-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_usercompany_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompany',
            name='contact_person',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='email',
            field=models.EmailField(blank=True, max_length=1500, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='position',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Position'),
        ),
    ]
