# Generated by Django 4.2 on 2025-03-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_course_duration_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='currency',
            field=models.IntegerField(choices=[(1, 'USD - United States Dollar'), (2, 'EUR - Euro'), (3, 'JPY - Japanese Yen'), (4, 'GBP - British Pound'), (5, 'AUD - Australian Dollar'), (6, 'CAD - Canadian Dollar'), (7, 'CHF - Swiss Franc'), (8, 'CNY - Chinese Yuan'), (9, 'SEK - Swedish Krona'), (10, 'NZD - New Zealand Dollar'), (11, 'MXN - Mexican Peso'), (12, 'SGD - Singapore Dollar'), (13, 'HKD - Hong Kong Dollar'), (14, 'NOK - Norwegian Krone'), (15, 'KRW - South Korean Won'), (16, 'TRY - Turkish Lira'), (17, 'INR - Indian Rupee'), (18, 'BRL - Brazilian Real'), (19, 'RUB - Russian Ruble'), (20, 'ZAR - South African Rand'), (21, 'MYR - Malaysian Ringgit'), (22, 'PHP - Philippine Peso'), (23, 'IDR - Indonesian Rupiah'), (24, 'THB - Thai Baht'), (25, 'PLN - Polish Zloty'), (26, 'CZK - Czech Koruna'), (27, 'HUF - Hungarian Forint'), (28, 'KRW - South Korean Won'), (29, 'ILS - Israeli Shekel'), (30, 'SAR - Saudi Riyal'), (31, 'AED - United Arab Emirates Dirham'), (32, 'EGP - Egyptian Pound'), (33, 'COP - Colombian Peso'), (34, 'VND - Vietnamese Dong'), (35, 'NGN - Nigerian Naira'), (36, 'PKR - Pakistani Rupee'), (37, 'KWD - Kuwaiti Dinar'), (38, 'QAR - Qatari Riyal'), (39, 'OMR - Omani Rial'), (40, 'BDT - Bangladeshi Taka')], null=True, verbose_name='Currency'),
        ),
    ]
