# Generated by Django 4.2 on 2025-03-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_course_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='currency',
            field=models.CharField(choices=[('AZN', 'Azərbaycan Manatı'), ('USD', 'United States Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('SEK', 'Swedish Krona'), ('NZD', 'New Zealand Dollar'), ('MXN', 'Mexican Peso'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('NOK', 'Norwegian Krone'), ('KRW', 'South Korean Won'), ('TRY', 'Turkish Lira'), ('INR', 'Indian Rupee'), ('BRL', 'Brazilian Real'), ('RUB', 'Russian Ruble'), ('ZAR', 'South African Rand'), ('MYR', 'Malaysian Ringgit'), ('PHP', 'Philippine Peso'), ('IDR', 'Indonesian Rupiah'), ('THB', 'Thai Baht'), ('PLN', 'Polish Zloty'), ('CZK', 'Czech Koruna'), ('HUF', 'Hungarian Forint'), ('KRW', 'South Korean Won'), ('ILS', 'Israeli Shekel'), ('SAR', 'Saudi Riyal'), ('AED', 'United Arab Emirates Dirham'), ('EGP', 'Egyptian Pound'), ('COP', 'Colombian Peso'), ('VND', 'Vietnamese Dong'), ('NGN', 'Nigerian Naira'), ('PKR', 'Pakistani Rupee'), ('KWD', 'Kuwaiti Dinar'), ('QAR', 'Qatari Riyal'), ('OMR', 'Omani Rial'), ('BDT', 'Bangladeshi Taka')], max_length=5, null=True, verbose_name='Currency'),
        ),
    ]
