# Generated by Django 4.2 on 2025-01-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_usercompany_contact_person_usercompany_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercompany',
            name='contact_person',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Contact Person Name'),
        ),
    ]
