# Generated by Django 4.2 on 2025-01-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_usercompany_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Last Name'),
        ),
    ]
