# Generated by Django 4.2 on 2025-04-19 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_course_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='course_or_trainings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.course', verbose_name='Course or Trainings'),
        ),
    ]
