# Generated by Django 4.2 on 2025-01-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_contactperson_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='name',
            new_name='first_name',
        ),
    ]
