# Generated by Django 4.2 on 2025-01-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_rename_name_contactperson_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercompany',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='usercompany',
            name='first_name',
            field=models.CharField(blank=True, max_length=1500, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='usercompany',
            name='last_name',
            field=models.CharField(blank=True, max_length=1500, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='first_name',
            field=models.CharField(max_length=1500, verbose_name='First Name'),
        ),
    ]
