# Generated by Django 4.2 on 2025-01-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_usercompany_contact_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='crm.usercompany', verbose_name='User Company'),
        ),
    ]
