# Generated by Django 4.2 on 2025-01-22 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_order_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_orders', to='crm.course', verbose_name='Course'),
        ),
    ]
