# Generated by Django 4.2 on 2025-01-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_order_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Slug'),
        ),
    ]
