# Generated by Django 4.2 on 2025-01-25 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_company_owner'),
        ('crm', '0017_order_slug_alter_contactperson_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='Task ID')),
                ('title', models.CharField(max_length=1200, verbose_name='Title')),
                ('task_type', models.IntegerField(choices=[(1, 'Personal'), (2, 'Phone Call'), (3, 'Message'), (4, 'Email')], verbose_name='Task Type')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deadline', models.DateTimeField(verbose_name='Due Date')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')], verbose_name='Priority')),
                ('status', models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Done')], verbose_name='Task Status')),
                ('slug', models.SlugField(editable=False, max_length=150, null=True, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Task Author')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Task Company')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-id'],
            },
        ),
    ]
