# Generated by Django 4.2 on 2025-01-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_calendarevent_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['-id'], 'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendars'},
        ),
    ]
