# Generated by Django 4.2 on 2025-02-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_calendarevent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='set_today',
            field=models.BooleanField(default=False, verbose_name='Set Today'),
        ),
    ]
