# Generated by Django 4.2 on 2025-02-15 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_company_address_company_company_logo_company_email_and_more'),
        ('crm', '0021_task_set_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Task Author'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Task Company'),
        ),
    ]
