# Generated by Django 4.2 on 2025-02-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_alter_calendarevent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='attendees',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Attendees email'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[(1, 'Meeting'), (2, 'Appointment'), (3, 'Event')], max_length=10, null=True, verbose_name='Event Type'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(blank=True, choices=[('#007bff', 'Blue'), ('#28a745', 'Green'), ('#dc3545', 'Red'), ('#ffc107', 'Yellow'), ('#17a2b8', 'Cyan'), ('#6f42c1', 'Purple'), ('#fd7e14', 'Orange'), ('#e83e8c', 'Pink'), ('#20c997', 'Teal'), ('#343a40', 'Dark'), ('#6c757d', 'Gray')], max_length=10),
        ),
    ]
