# Generated by Django 4.2 on 2025-02-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_notification_notificationview'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Company'), (3, 'Order'), (4, 'Task'), (5, 'Calendar')], null=True, verbose_name='Type'),
        ),
    ]
