# Generated by Django 4.2 on 2025-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_notification_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action_type',
            field=models.IntegerField(choices=[(1, 'Add'), (2, 'Edit')], null=True, verbose_name='Type'),
        ),
    ]
