# Generated by Django 4.2 on 2025-02-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_alter_notification_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
    ]
